# Generated by Django 4.2.7 on 2023-12-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalreports',
            name='medical_report',
            field=models.FileField(upload_to='medical_reports/'),
        ),
    ]
